import { deriveCompanyCode } from "@/lib/types/contact";

/** Auto-generated from Connect Dots masterlist — client codes */
export type ClientCodeEntry = { code: string; name: string };

export const CLIENT_CODES: ClientCodeEntry[] = [
  { code: "AP", name: "ALBINO & PRETO" },
  { code: "APT", name: "Apartment4B" },
  { code: "BA", name: "Born Again" },
  { code: "BAV", name: "Bavel" },
  { code: "BEV", name: "Beverly Beach" },
  { code: "BKT", name: "Black Kids Travel" },
  { code: "BLK", name: "Black Angel" },
  { code: "BLS", name: "Black Santa" },
  { code: "BPB", name: "BackPack Boyz" },
  { code: "CAC", name: "Coffee & Clothes" },
  { code: "CAM", name: "Camber" },
  { code: "CAS", name: "Caspian Queen" },
  { code: "CC", name: "Cosmic Crown" },
  { code: "CD", name: "Connect Dots" },
  { code: "CDG", name: "Capital Design Group" },
  { code: "CHF", name: "Childhood Friend" },
  { code: "CM", name: "Casa Murano" },
  { code: "CO", name: "Consolidated Solids" },
  { code: "CS", name: "Creep Street" },
  { code: "DNA", name: "DNA Merch" },
  { code: "ELS", name: "Eleven Sixteen" },
  { code: "ESG", name: "Eastside Golf" },
  { code: "FC", name: "Full Court" },
  { code: "FER", name: "Ferrari Sheppard" },
  { code: "FF", name: "Fyre Fit" },
  { code: "FL", name: "Flippers" },
  { code: "FLO", name: "Flowin" },
  { code: "FS", name: "Five Star" },
  { code: "GAL", name: "BB Galpin" },
  { code: "GG", name: "Glo Gang" },
  { code: "GO", name: "Goda LLC" },
  { code: "HAR", name: "Harun" },
  { code: "HC", name: "Homecoming" },
  { code: "HHC", name: "Hip Hop Caucus" },
  { code: "HS", name: "Hillsong" },
  { code: "IND", name: "Indo" },
  { code: "IQ", name: "IQ" },
  { code: "JBH", name: "Jason of Beverly Hills" },
  { code: "JU", name: "Juice" },
  { code: "KS", name: "Kira Stokes" },
  { code: "LAM", name: "Lambo4oe" },
  { code: "LN", name: "Live Nation" },
  { code: "LNQ", name: "LNQ" },
  { code: "LO", name: "Lion Order" },
  { code: "LS", name: "Little Saigon" },
  { code: "LSD", name: "Life Skin Deep" },
  { code: "MAU", name: "Maurice" },
  { code: "MAR", name: "Marvito" },
  { code: "MB", name: "Midnite" },
  { code: "MC", name: "Mint Condition" },
  { code: "MH", name: "Mayer Hawthorne" },
  { code: "MK", name: "Make Matcha" },
  { code: "MMS", name: "Master Manufacturing Systems" },
  { code: "NMC", name: "No Man Curse" },
  { code: "NMC", name: "No Man Curse" },
  { code: "NOX", name: "Nox" },
  { code: "NWM", name: "Nu Wave Music" },
  { code: "NYS", name: "Not Your Standard" },
  { code: "OPH", name: "Ophelia" },
  { code: "OPM", name: "OPM" },
  { code: "PEAR", name: "Pear" },
  { code: "PG", name: "Playground" },
  { code: "PHO", name: "Pho 87" },
  { code: "QOR", name: "Qore" },
  { code: "RB", name: "Rare Beauty" },
  { code: "RC", name: "Real Controversial" },
  { code: "REL", name: "RELYK" },
  { code: "ROC", name: "Roc Nation" },
  { code: "SBE", name: "SBE" },
  { code: "SG", name: "Santigold" },
  { code: "SH", name: "Seventh Heaven" },
  { code: "SHA", name: "Sharon Stone" },
  { code: "SM", name: "Seven Minds" },
  { code: "SM", name: "SuperMax" },
  { code: "SS", name: "Ssur" },
  { code: "SY", name: "Syera" },
  { code: "TAM", name: "Tracy Anderson Method" },
  { code: "TEN", name: "10 Summers" },
  { code: "TER", name: "Terroni" },
  { code: "TFC", name: "The Friend Club" },
  { code: "TOL", name: "Tollé" },
  { code: "UNG", name: "Unguarded" },
  { code: "UNS", name: "Underscores" },
  { code: "VC", name: "Vita Coco" },
  { code: "VIO", name: "Viola" },
  { code: "VOS", name: "VOID STAR" },
  { code: "VS", name: "Vivi's World" },
  { code: "WOS", name: "World of Sorrows" },
  { code: "WS", name: "WaveSpace" },
  { code: "YOO", name: "Yool" },
  { code: "ZOE", name: "ZOE" },
];

export function clientCodeByName(name: string): string | null {
  const n = name.trim().toLowerCase();
  const hit = CLIENT_CODES.find((c) => c.name.toLowerCase() === n);
  return hit?.code ?? null;
}

/** Client code for PO / project numbers — catalog match, then brand initials (e.g. ZOE Conference → ZC). */
export function resolveClientCode(name: string): string {
  const trimmed = name.trim();
  if (!trimmed) return "XX";
  const exact = clientCodeByName(trimmed);
  if (exact) return exact;
  const lower = trimmed.toLowerCase();
  const prefix = CLIENT_CODES.find((c) => {
    const cn = c.name.toLowerCase();
    return lower === cn || lower.startsWith(`${cn} `) || lower.startsWith(`${cn}-`);
  });
  if (prefix) return prefix.code;
  return deriveCompanyCode(trimmed);
}

/** Max style sequence per style prefix (e.g. GGT -> 148) */
export const STYLE_PREFIX_MAX_SEQ: Record<string, number> = {
  "ADH": 1,
  "AGT": 1,
  "APH": 3,
  "ASSW": 2,
  "AST": 5,
  "BAU": 1,
  "BAVH": 1,
  "BBGT": 3,
  "BEVP": 1,
  "BEVSW": 3,
  "BHMCH": 1,
  "BLKP": 1,
  "BLKSW": 3,
  "BLKT": 3,
  "BLSSW": 1,
  "BOGP": 1,
  "BOGSW": 3,
  "BOGT": 1,
  "BZNT": 1,
  "CAMH": 1,
  "CAMSW": 1,
  "CAMT": 1,
  "CDH": 1,
  "CDTT": 3,
  "CHEA": 1,
  "CHFH": 1,
  "CHFSW": 1,
  "CORHG": 1,
  "CORT": 2,
  "COT": 12,
  "CSB": 1,
  "CST": 2,
  "CSU": 5,
  "CVT": 1,
  "DNAH": 1,
  "DNASW": 2,
  "DNAT": 3,
  "ELSP": 1,
  "ELSSW": 1,
  "ELST": 1,
  "EMAA": 1,
  "EMAH": 1,
  "EMAHG": 2,
  "EMAP": 2,
  "EMAT": 2,
  "ESBA": 1,
  "ESBT": 2,
  "ESGH": 7,
  "FCSW": 1,
  "FERSW": 4,
  "FFJ": 1,
  "FFP": 3,
  "FFSH": 1,
  "FFT": 3,
  "FFU": 2,
  "FLA": 5,
  "FLOT": 1,
  "FLST": 9,
  "GALB": 1,
  "GALH": 3,
  "GALSW": 2,
  "GALT": 8,
  "GGA": 5,
  "GGH": 6,
  "GGJ": 5,
  "GGP": 24,
  "GGSB": 9,
  "GGSH": 12,
  "GGST": 24,
  "GGSW": 85,
  "GGT": 148,
  "GGU": 5,
  "GTBSW": 1,
  "HARH": 1,
  "HARHG": 3,
  "HARP": 1,
  "HARSW": 3,
  "HART": 6,
  "HCA": 1,
  "HCH": 2,
  "HCJ": 1,
  "HCSW": 1,
  "HCT": 1,
  "HCWH": 1,
  "HCWSW": 1,
  "HCWT": 2,
  "HDLA": 2,
  "HDLJ": 1,
  "HDLSW": 2,
  "HDLT": 2,
  "HHCA": 13,
  "HHCH": 8,
  "HHCJ": 1,
  "HHCSW": 4,
  "HHCT": 6,
  "HOLH": 1,
  "HOLP": 1,
  "HOLSW": 2,
  "HOLT": 7,
  "HSA": 2,
  "HSH": 2,
  "INDH": 1,
  "INDP": 1,
  "INDSW": 1,
  "INDSWO": 2,
  "INDT": 2,
  "JBHHG": 1,
  "JYHG": 1,
  "KNWNH": 2,
  "KNWNT": 3,
  "KSA": 1,
  "KSSW": 1,
  "LNQA": 1,
  "LNQB": 1,
  "LNQSW": 5,
  "LOSW": 2,
  "LSDJ": 1,
  "LSDSW": 8,
  "LSDT": 11,
  "LSH": 2,
  "LSSW": 1,
  "LST": 13,
  "MAJ": 1,
  "MAJH": 1,
  "MAJHG": 3,
  "MAJPG": 7,
  "MANH": 2,
  "MANST": 4,
  "MARSW": 1,
  "MBHG": 1,
  "MCT": 2,
  "MCU": 3,
  "MHT": 2,
  "NMBP": 1,
  "NMBSW": 1,
  "NMCJ": 1,
  "NMCT": 7,
  "NOXH": 1,
  "NOXSW": 2,
  "NOXT": 1,
  "NWMSW": 2,
  "NYSHG": 1,
  "OPHU": 3,
  "OPMB": 1,
  "OPMH": 1,
  "OPMP": 1,
  "PBHG": 1,
  "PDU": 1,
  "PGOJ": 1,
  "PGOSW": 2,
  "PGOT": 2,
  "PGT": 1,
  "PHOB": 2,
  "PHOH": 2,
  "PHOT": 19,
  "PKST": 2,
  "QORP": 1,
  "QORSH": 2,
  "QORSK": 2,
  "QORSW": 9,
  "QORT": 5,
  "RBP": 1,
  "RBSW": 1,
  "RCP": 1,
  "RCSW": 1,
  "SBEH": 1,
  "SEHB": 1,
  "SGB": 1,
  "SGENSW": 1,
  "SGH": 2,
  "SGPG": 3,
  "SGSW": 3,
  "SGT": 14,
  "SHAP": 1,
  "SHOSW": 1,
  "SHOT": 2,
  "SHP": 1,
  "SHSW": 2,
  "SMA": 1,
  "SMP": 1,
  "SMT": 1,
  "SMU": 1,
  "SPSW": 1,
  "SSA": 2,
  "SSH": 1,
  "SSHG": 1,
  "SSP": 1,
  "SSSW": 2,
  "SST": 9,
  "TAM": 1,
  "TBT": 9,
  "TEN": 3,
  "TENH": 1,
  "TENJ": 1,
  "TENSW": 2,
  "TENT": 2,
  "TERH": 4,
  "TERSW": 1,
  "TERT": 1,
  "THUH": 1,
  "TOLA": 1,
  "TRA": 4,
  "TRGT": 3,
  "TRISW": 1,
  "TRIT": 2,
  "UNGJ": 16,
  "UNGKN": 1,
  "UNGP": 12,
  "UNGSH": 5,
  "UNGSW": 5,
  "UNGT": 7,
  "VCH": 2,
  "VCHG": 1,
  "VCSW": 1,
  "VCT": 3,
  "VDLB": 1,
  "VDLH": 1,
  "VIOJ": 1,
  "VIOSH": 1,
  "VIOSW": 1,
  "VIOT": 2,
  "VIVU": 5,
  "VOSSW": 1,
  "VOST": 8,
  "WHPP": 1,
  "WOSSW": 2,
  "WOST": 4,
  "XPJ": 1,
  "ZIMB": 1,
  "ZOE": 2,
  "ZOEA": 2,
  "ZOEH": 19,
  "ZOEP": 1,
  "ZOESH": 2,
  "ZOESW": 17,
  "ZOET": 24,
};
