/** Rows returned from Supabase `projects` + joined client contact. */
export type ProjectRowDb = {
  id: number;
  name: string;
  description: string | null;
  project_number: string | null;
  due_date: string | null;
  status: string;
  status_overview: string | null;
  status_update_date: string | null;
  style_number: string | null;
  style_name: string | null;
  category: string | null;
  type: string | null;
  lead_vendor: string | null;
  lead_team_member: string | null;
  client_meeting_date: string | null;
  client_assets_received_date: string | null;
  cs_tech_pack_request_date: string | null;
  cs_tech_pack_due_date: string | null;
  cs_tech_pack_assigned_member: string | null;
  cs_tech_pack_complete_date: string | null;
  artwork_tech_pack_request_date: string | null;
  artwork_tech_pack_due_date: string | null;
  artwork_tech_pack_assigned_member: string | null;
  artwork_tech_pack_complete_date: string | null;
  artwork_design_client_approval_date: string | null;
  dev_prod_assigned_team_member: string | null;
  tp_sent_date: string | null;
  references_sent_date: string | null;
  quote_requested_date: string | null;
  vendor_costing_received_date: string | null;
  cost_sheet_prepared_date: string | null;
  estimate_sent_date: string | null;
  costing_approved: boolean | null;
  dye_vendor: string | null;
  lab_dip_request_date: string | null;
  lab_dip_due_date: string | null;
  lab_dip_received_date: string | null;
  lab_dip_approval_status: string | null;
  print_embroidery_vendor: string | null;
  strike_off_request_date: string | null;
  strike_off_due_date: string | null;
  strike_off_received_date: string | null;
  strike_off_approval_status: string | null;
  bulk_fabric_approval_date: string | null;
  bulk_trim_approval_date: string | null;
  new_product_request_date: string | null;
  barcodes_sent_to_vendor_date: string | null;
  top_due_date: string | null;
  top_approved_date: string | null;
  bulk_target_delivery_date: string | null;
  ex_factory_date: string | null;
  shipping_terms: string | null;
  shipping_method: string | null;
  packing_list_received_date: string | null;
  tracking_bol_number: string | null;
  packing_list_sent_to_client_date: string | null;
  client_received_date: string | null;
  colorways: unknown;
  in_development: unknown;
  client?: {
    id: number;
    name: string;
    avatar_url: string | null;
  } | null;
};

export type ContactRowDb = {
  id: number;
  user_id?: string;
  name: string;
  email: string;
  phone: string | null;
  company_name: string | null;
  avatar_url: string | null;
  role: string;
  linked_auth_user_id?: string | null;
  has_unread: boolean;
  website: string | null;
  address: string | null;
  project_ids: number[] | null;
  created_at?: string;
  updated_at?: string;
};

export type ProjectOrderRowDb = {
  id: string;
  user_id: string;
  project_id: number;
  order_number: string;
  due_date: string | null;
  po_number: string | null;
  client_po_number: string | null;
  linked_order_ids: unknown;
  created_at?: string;
  updated_at?: string;
};

export type ProjectJobRowDb = {
  id: string;
  project_id: number;
  order_id?: string | null;
  job_number: string | null;
  name: string;
  subtitle: string | null;
  job_type: string | null;
  status: string;
  due_date: string | null;
  updated_at: string;
  wip: Record<string, unknown>;
};
