import type { LedgerSeed } from "@/lib/ledger/types";

/** Master ledger data — edit here until a backend exists. */
export const LEDGER_SEED: LedgerSeed = {
  disclaimer: "Monthly payments are drawdowns against project value.",

  onpro: {
    capCents: 7_500_000,
    monthlyRetainerCents: 300_000,
    includedInCap: [
      "OnPro iOS application",
      "OnPro Next.js workspace",
      "Supabase backend & Next.js API (Node)",
      "OnPro admin platform",
      "Authentication & permissions",
      "Messaging infrastructure",
      "Production workflows",
      "Production-ready foundation",
      "DevOps server setup and management",
      "Enterprise / ERP integrations",
      "AI systems & automation",
    ],
  },

  /** Major systems — sums to $75,000. Drives accrued $ and work-finished %. */
  capSystems: [
    {
      id: "cap-ios",
      label: "OnPro iOS application",
      status: "in_progress",
      statusLabel: "95% Complete",
      completionFraction: 0.95,
      valueCents: 2_500_000,
      weight: 25,
    },
    {
      id: "cap-next",
      label: "OnPro Next.js workspace",
      status: "in_progress",
      statusLabel: "94% Complete",
      completionFraction: 0.94,
      valueCents: 2_000_000,
      weight: 20,
    },
    {
      id: "cap-supabase-api",
      label: "Supabase backend & Next.js API (Node)",
      status: "in_progress",
      statusLabel: "~86% Complete",
      completionFraction: 0.86,
      valueCents: 2_000_000,
      weight: 20,
    },
    {
      id: "cap-admin",
      label: "OnPro admin platform",
      status: "pending",
      valueCents: 1_000_000,
      weight: 10,
    },
  ],

  /** Cap rows for phase 1/2 are derived from capSystems at load; only “included” rows live here. */
  phase1Frontend: [],

  phase2Backend: [
    {
      id: "p2-planning",
      label: "Backend + admin architecture planning",
      status: "complete",
      valueLabel: "Included",
    },
    {
      id: "p2-workflows",
      label: "Shared operational systems & workflow design",
      status: "included",
      valueLabel: "Included",
    },
  ],

  invoices: [
    {
      id: "inv-fbrc-wholesale",
      dateLabel: "TBD",
      label: "FBRC.LA — Site transfer & wholesale order expansion",
      amountCents: 150_000,
      status: "pending",
      projectId: "fbrc",
      kind: "other",
    },
    {
      id: "inv-onpro-jun-2026",
      dateLabel: "June 2026",
      label: "Monthly OnPro retainer",
      amountCents: 150_000,
      status: "pending",
      projectId: "onpro",
      kind: "retainer",
    },
    {
      id: "inv-onpro-jul-2026",
      dateLabel: "July 2026",
      label: "Monthly OnPro retainer",
      amountCents: 300_000,
      status: "pending",
      projectId: "onpro",
      kind: "retainer",
    },
  ],

  /** Dated deliverables — staggered across periods; shown below invoices for full accounting. */
  workRecords: [
    {
      id: "wr-ios-jan",
      periodLabel: "Jan 2026",
      sortKey: "2026-01",
      projectId: "onpro",
      description: "OnPro iOS application — app shell, Supabase auth, navigation",
      status: "completed",
    },
    {
      id: "wr-ios-feb",
      periodLabel: "Feb 2026",
      sortKey: "2026-02",
      projectId: "onpro",
      description: "OnPro iOS — projects, messaging, smart attachments, calendar, tab bar",
      status: "completed",
    },
    {
      id: "wr-next-scaffold",
      periodLabel: "May 2026",
      sortKey: "2026-05-14",
      projectId: "onpro",
      description: "OnPro Next.js workspace — desktop shell, project model parity with iOS",
      status: "completed",
    },
    {
      id: "wr-next-parity",
      periodLabel: "May 2026",
      sortKey: "2026-05-15a",
      projectId: "onpro",
      description: "Next.js — People, permissions, jobs, messaging, attachments",
      status: "completed",
    },
    {
      id: "wr-next-home",
      periodLabel: "May 2026",
      sortKey: "2026-05-15b",
      projectId: "onpro",
      description: "Next.js — Overview home, alerts, notifications",
      status: "completed",
    },
    {
      id: "wr-next-detail",
      periodLabel: "May 2026",
      sortKey: "2026-05-17",
      projectId: "onpro",
      description: "Project detail modules — client card, WIP, costing (mock)",
      status: "completed",
    },
    {
      id: "wr-next-production",
      periodLabel: "May 2026",
      sortKey: "2026-05-23",
      projectId: "onpro",
      description: "Production board, reference data, demo import pipeline",
      status: "completed",
    },
    {
      id: "wr-cap-ios",
      periodLabel: "May 2026",
      sortKey: "2026-05-cap-ios",
      projectId: "onpro",
      description: "OnPro iOS application — cap system (95% complete)",
      valueCents: 2_500_000,
      status: "completed",
    },
    {
      id: "wr-cap-next",
      periodLabel: "June 2026",
      sortKey: "2026-06-cap-next",
      projectId: "onpro",
      description: "OnPro Next.js workspace — cap system (94% complete)",
      valueCents: 2_000_000,
      status: "in_progress",
    },
    {
      id: "wr-next-jun-live",
      periodLabel: "June 2026",
      sortKey: "2026-06-live",
      projectId: "onpro",
      invoiceId: "inv-onpro-jun-2026",
      description: "Live Supabase path + data loaders",
      detail:
        "• Header Live/Mock toggle (`onpro_backend_mode` cookie) — **dev only**; hidden on Vercel\n• **Production Live-only** — Supabase env → Live data; mock cookie ignored (`backend-mode.ts`)\n• **Vercel deploy** — `c9025b8` to `main` (4 Jun); migrations **002–021** in repo\n• SSR Supabase client + middleware; login page; `.env.example` for `NEXT_PUBLIC_SUPABASE_*`\n• `live-cache.ts` + `LiveDataHydrator` for client hydration after server fetch; **`onpro-projects-changed`** event\n• `fetchProjects` / `fetchContacts` / `fetchJobs` via `src/lib/data/` + mappers\n• Mock stores gated: `project-session`, `contacts-store`, `project-wip-edits` respect Live\n• **BACKEND.md** — schema pointers, iOS `SupabaseService`, integration notes",
      status: "in_progress",
    },
    {
      id: "wr-next-jun-mailroom",
      periodLabel: "June 2026",
      sortKey: "2026-06-mailroom",
      projectId: "onpro",
      invoiceId: "inv-onpro-jun-2026",
      description: "Gmail Mailroom + agent inbox + conversational chat",
      detail:
        "• Google OAuth + `003_user_gmail.sql` (`user_gmail_connections`)\n• Routes: connect, callback, threads, summarize, apply, status, **chat** (`/api/mailroom/chat`)\n• Live threads from Gmail only; **images/attachments** in thread; dedupe on import\n• **Summarize-only** — new mail never auto-summarized; `012_mailroom_thread_scans.sql` cache (~1 year)\n• Summary UI — entity pills + footer hint removed; single Summarize helper line\n• **RFQ intake** — team/vendor selects; owner always in team + defaults self; vendor on project create; removed “On this thread” chips\n• Attachment **Show details** → document preview modal\n• Agent apply → generated items + mailroom state; conversational chat (`chat-intent.ts`)\n• **Gmail token expiry** — reauth prompt when Google token expired (`gmail/auth-errors.ts`)\n• Connect hero; promote-to-mailroom from Messages",
      status: "in_progress",
    },
    {
      id: "wr-next-jun-onboarding",
      periodLabel: "June 2026",
      sortKey: "2026-06-onboarding",
      projectId: "onpro",
      invoiceId: "inv-onpro-jun-2026",
      description: "Onboarding + profiles + avatars",
      detail:
        "• `004_profiles_onboarding.sql` — operator **4 steps** (workspace → business → team → launch); client 2-step → Messages\n• **Member onboarding** — `/api/onboarding/member` for team/vendor invite accept\n• **Step 3 polish** — centered blurb + celebration graphic alignment\n• **First login** → **`/` (OnPro AI)** after onboarding (not Projects)\n• **Signup intent** — client vs operator on landing/login before account creation\n• Client onboarding **step 2** — workspace join cards when email matches operator workspace\n• Routes: `/api/onboarding/status`, `/operator`, `/client`, `/init`, `/workspace-matches`, `/join-workspace`; middleware gate; `ensureSelfTeamContact`\n• `005_storage_avatars.sql` + upload; `006_workspace_welcome.sql`; `/api/profile` GET/PATCH",
      status: "in_progress",
    },
    {
      id: "wr-next-jun-contacts",
      periodLabel: "June 2026",
      sortKey: "2026-06-contacts",
      projectId: "onpro",
      invoiceId: "inv-onpro-jun-2026",
      description: "Contacts directory, import, modals",
      detail:
        "• **Contacts** nav (route `/people`): Live `POST /api/contacts`, persist + permissions\n• Add client / teammate / vendor modals — teammate copy **“Add a teammate to Contacts.”**\n• **Resend invite** — `POST /api/invites/resend` on pending contact cards\n• **Delete safety** — project delete never removes Contacts; `self_contact_id` protected\n• **CSV import** — AI + fallback; editable review; auto-chunk batches (200 rows); sample file\n• **Live invites** — `/api/invites/create`, resolve token on login, copy-link toast\n• Project roster dedupe",
      status: "in_progress",
    },
    {
      id: "wr-next-jun-welcome-ai",
      periodLabel: "June 2026",
      sortKey: "2026-06-welcome",
      projectId: "onpro",
      invoiceId: "inv-onpro-jun-2026",
      description: "Workspace welcome + OnPro AI positioning",
      detail:
        "• `WorkspaceWelcomeGate` after onboarding; dismiss → `profiles.workspace_welcome_dismissed_at` + mock/session fallback\n• **Your teams** — workspace match list on OnPro AI when signup email matches operators (`013`)\n• Sidebar **OnPro AI** first (was Overview); command palette updated\n• `/api/assistant/briefing` + `/api/assistant/chat`; Live briefing from real snapshot\n• **Google Calendar** on overview right rail — workspace team events; hydration loop fix\n• **Project dedupe** — `workspace-split-jobs.ts` won’t duplicate existing projects\n• **Briefing section prefs** — `007_assistant_prefs.sql`; opt-out per section on Update me\n• `assistant-message-parts.tsx`, `workspace-welcome-reply.ts` intent routing",
      status: "in_progress",
    },
    {
      id: "wr-next-jun-projects-ux",
      periodLabel: "June 2026",
      sortKey: "2026-06-projects-ux",
      projectId: "onpro",
      invoiceId: "inv-onpro-jun-2026",
      description: "Projects UX + Live create/edit API",
      detail:
        "• `new-project-modal.tsx` — split layout; slide-in **add client** (company/individual, `commitSingleContact`)\n• `OPEN_NEW_PROJECT_EVENT` from workspace welcome\n• Live: `POST`/`PATCH` `/api/projects`, `persist-project.ts`, `insertProjectForUser` / `updateProjectForUser`\n• List stays on `/projects` after create; `?cover=1` cleared; **instant refresh** via `onpro-projects-changed`\n• **Client code mismatch** — amber notice + effective PO from `client-code-resolve.ts`\n• **Status funnel** — Intake / On Hold / Development / Production / Completed; `projectStatusToDb()`\n• **Team project create** — workspace owner on insert; `021_projects_member_write.sql` + service role path\n• **Hydration fix** — stable dates, deferred client merge (React #418)\n• Modal polish: removed bottom emoji illustrations (shared `ProjectModalAside` pattern)",
      status: "in_progress",
    },
    {
      id: "wr-next-jun-covers",
      periodLabel: "June 2026",
      sortKey: "2026-06-covers",
      projectId: "onpro",
      invoiceId: "inv-onpro-jun-2026",
      description: "Section connect covers (all ops areas)",
      detail:
        "• `section-cover.ts`, `ops-section-cover.tsx`, per-section `*-connect-hero.tsx`\n• Covers: Projects, Jobs, Messages, Mailroom, **Contacts**, Calendar, Documents\n• Page header ℹ️ → `?cover=1`; auto-hide when section already has content\n• Jobs cover CTA “Open projects” when projects exist but no jobs",
      status: "in_progress",
    },
    {
      id: "wr-next-jun-jobs-ux",
      periodLabel: "June 2026",
      sortKey: "2026-06-jobs-ux",
      projectId: "onpro",
      invoiceId: "inv-onpro-jun-2026",
      description: "Jobs UX — create flow + modal polish",
      detail:
        "• `+ New job` on Jobs header; `CreateJobLauncher` + **project picker** on all add-job paths\n• `job-details-modal.tsx` — wide-tall overlay; **section nav in left violet column**; share menu\n• **Style name** below job name; **Style #** for apparel workspaces (`workspace-industry.ts`)\n• **Multi-colorway editor** — dropdown picker, auto abbrev codes, size range + per-size qty + total\n• **Price from costing** — default from costing sheet; manual override (`job-price.ts`)\n• **Orders on first job** — no phantom order until first job saved\n• **Live job defaults** — no hardcoded `GGT149` style #; mock timeline tasks stripped; `job-status-badge.tsx`\n• `demo-seed-jobs.ts` strip in Live; `live-cache` / `project-detail-gate` — jobs not wiped on hydrate\n• **Project detail Jobs tab** — `loadProjectJobs()` + `onpro-jobs-changed` (matches Production board)\n• Custom field name typing fix in job modal\n• Open: **job modal save → Supabase** (still localStorage + cache)",
      status: "in_progress",
    },
    {
      id: "wr-next-jun-jobs",
      periodLabel: "June 2026",
      sortKey: "2026-06-jobs",
      projectId: "onpro",
      invoiceId: "inv-onpro-jun-2026",
      description: "Costing, estimates, production depth",
      detail:
        "• Costing sheet editor, templates, print helpers, estimates list\n• Vendor quotes + tech pack artwork sections in job details\n• `job-development.ts`, `job-timeline-templates.ts`, `job-number.ts`\n• Production board — WIP, labels, packing-slip integration with job modal",
      status: "in_progress",
    },
    {
      id: "wr-next-jun-assistant-profile",
      periodLabel: "June 2026",
      sortKey: "2026-06-assistant",
      projectId: "onpro",
      invoiceId: "inv-onpro-jun-2026",
      description: "Assistant API + full ops snapshot",
      detail:
        "• `buildAssistantOpsSnapshot` — projects (rich), jobs (WIP steps), contacts (≤100), in-app messages, Mailroom/Gmail bodies (trimmed), documents/calendar (mock), `coverage` JSON\n• Prompts forbid “I don’t have access”; `briefing-part-spacing.ts` for readable project lists\n• `assistant-prompt-trim.ts`; mock/live fallbacks when API fails\n• Settings → Your account: name, company, phone, address → Supabase `profiles`\n• Sidebar footer: avatar + display name; `profiles.username` from onboarding\n• Settings infinite-loop bugfix",
      status: "in_progress",
    },
    {
      id: "wr-next-jun-ui-docs",
      periodLabel: "June 2026",
      sortKey: "2026-06-ui",
      projectId: "onpro",
      invoiceId: "inv-onpro-jun-2026",
      description: "Runbooks, messaging decision, UI polish",
      detail:
        "• **Live Messages** — `009_in_app_messages.sql` + `/api/messages/*`; image storage `010`; no fake online indicators\n• **Google Calendar** — read path + next-6-meetings sidebar; calendar event AI modal\n• **Documents** — preview modal; image delete + confirm; project delete cascades images\n• **Invoice editor** — `/ledger/financial/invoices/new` + `[id]`; `ledger-invoice-editor.tsx`, draft/print helpers\n• Notifications bell only when items exist; owner join events (`/api/workspace/member-events`)\n• Messages — **Add Member** on conversations\n• Modal UX — removed bottom emoji illustrations across polished modals\n• **Ledger UI** — expandable work rows, month-only period labels, retainer-only June invoice\n• `docs/MESSAGING_DECISION.md`, `docs/development-ledger/` sprint notes",
      status: "in_progress",
    },
    {
      id: "wr-next-jun-workspace-link",
      periodLabel: "June 2026",
      sortKey: "2026-06-workspace",
      projectId: "onpro",
      invoiceId: "inv-onpro-jun-2026",
      description: "Client signup + workspace linking",
      detail:
        "• `008_workspace_memberships.sql` — memberships, `pending_invites`, `workspace_member_events`, `contacts.linked_auth_user_id`\n• **`013_workspace_member_team_vendor.sql`** — Team + Vendor email match + join; member project read RLS\n• RPCs: `find_workspaces_for_email`, `join_workspace`, `revoke_workspace_membership`, `resolve_invite_token`\n• APIs: workspace-matches, join-workspace, `/api/invites/*` (create, resolve, **resend**), memberships, member-events\n• Invite token links for client / team / vendor; client confirm-to-join; owner revoke on contact detail\n• Open: iOS parity, messages RLS edge cases",
      status: "in_progress",
    },
    {
      id: "wr-next-jun-entry-ops",
      periodLabel: "June 2026",
      sortKey: "2026-06-entry-ops",
      projectId: "onpro",
      invoiceId: "inv-onpro-jun-2026",
      description: "Job entry + project create (live ops feedback)",
      detail:
        "• **Client code resolve** — detect stored vs master-list mismatch (e.g. FFS vs FER); amber notice on new project; effective PO uses resolved code\n• **Project status funnel** — Intake → On Hold → Development → Production → Completed; DB mapping (`projectStatusToDb`)\n• **Job entry (apparel)** — Style name, Style #, multi-colorway dropdown + auto codes, size breakdown, price from costing\n• **Orders deferred** — no order row until first job saved (CD… prefix after first job)\n• **Team project create** — workspace owner resolution; migration **021** member write RLS; service role fallback\n• **Projects list refresh** — `onpro-projects-changed` cache event; hydration hardening (React #418)\n• **Gmail reauth** — expired Google token detection in Mailroom/Calendar\n• **Invoice editor scaffold** — `/ledger/financial/invoices/*`, draft types, print helper\n• Open: persist `company_code_confirmed` to contact JSON; job modal save → Supabase",
      status: "in_progress",
    },
    {
      id: "wr-ios-jul-backend",
      periodLabel: "July 2026",
      sortKey: "2026-07-ios",
      projectId: "onpro",
      invoiceId: "inv-onpro-jul-2026",
      description: "iOS backend connection + app updates",
      detail:
        "• Wire OnPro iOS to shared Supabase backend (`SupabaseService` — projects, contacts, jobs, profiles)\n• Align auth/session, data mappers, and read/write paths with desktop Live mode\n• App updates for parity with June desktop deliverables (Mailroom, onboarding, assistant where applicable)",
      status: "pending",
    },
    {
      id: "wr-planning",
      periodLabel: "May 2026",
      sortKey: "2026-05-plan",
      projectId: "onpro",
      description: "Backend + admin architecture planning",
      valueLabel: "Included",
      status: "completed",
    },
    {
      id: "wr-supabase-api",
      periodLabel: "June 2026",
      sortKey: "2026-06-supabase",
      projectId: "onpro",
      description: "Supabase + Node APIs (~86% cap system)",
      detail:
        "Shipped in Live: auth/middleware (~100%); projects POST/PATCH + orders 011 + team write 021 + status funnel (~97%); contacts/permissions + resend (~92%); profiles, onboarding, member flow, `/api/profile` (~96%); **workspace memberships + invites (~90%, 008 + 013)**; assistant prefs + Your teams (~92%); Mailroom Gmail + RFQ + 012 scans + token reauth (~93%); assistant briefing/chat + dedupe (~90%); jobs read + hydrate + rich entry UX (~52% — modal save still LS); **messages Live read/send (~72%, 009 + 010)**; **Google Calendar read (~55%)**; **documents preview/delete (~35%)**.\nStill open: job WIP write path, documents index DB, calendar write-back, messages RLS polish, company_code_confirmed persist.",
      valueCents: 2_000_000,
      status: "in_progress",
    },
    {
      id: "wr-admin",
      periodLabel: "Not started",
      sortKey: "2026-99-admin",
      projectId: "onpro",
      description: "OnPro admin platform",
      valueCents: 1_000_000,
      status: "pending",
    },
    {
      id: "wr-fbrc-transfer",
      periodLabel: "TBD",
      sortKey: "2099-fbrc-transfer",
      projectId: "fbrc",
      description: "FBRC.LA — Site transfer & wholesale order expansion",
      valueCents: 150_000,
      status: "pending",
    },
  ],

  /** Phase 3 — AI & automation deliverables (weight = progress share, not dollars). */
  milestones: [
    {
      id: "ms-ai-overview",
      phase: 3,
      label: "OnPro AI — overview briefing & chat API",
      weight: 20,
      status: "complete",
    },
    {
      id: "ms-ai-welcome",
      phase: 3,
      label: "Workspace welcome assistant & intent routing",
      weight: 8,
      status: "complete",
    },
    {
      id: "ms-ai-snapshot",
      phase: 3,
      label: "Workspace ops snapshot for LLM (projects, jobs, contacts, coverage)",
      weight: 15,
      status: "complete",
    },
    {
      id: "ms-ai-mailroom",
      phase: 3,
      label: "Mailroom — summarize, apply suggestions & conversational chat",
      weight: 12,
      status: "complete",
    },
    {
      id: "ms-ai-production",
      phase: 3,
      label: "Production assistance — timelines, delays, missing approvals",
      weight: 15,
      status: "pending",
    },
    {
      id: "ms-ai-docs",
      phase: 3,
      label: "Document intelligence — POs, invoices, shipment extraction",
      weight: 15,
      status: "pending",
    },
    {
      id: "ms-ai-ops-recs",
      phase: 3,
      label: "Operational recommendations & deep workflow automation",
      weight: 15,
      status: "pending",
    },
  ],

  futureExpansion: [
    { id: "fe-android", label: "Android application", status: "TBD" },
    { id: "fe-analytics", label: "Advanced analytics & reporting", status: "TBD" },
  ],

  expandableScope: [],

  dropx: [
    { label: "Equity structure", value: "Founder-level" },
    { label: "Current billing", value: "Deferred" },
    { label: "Cash compensation", value: "None currently" },
    { label: "Product direction", value: "Active" },
    { label: "UI / platform concepts", value: "Built" },
    { label: "Funding strategy", value: "Pending" },
    { label: "Purpose", value: "Fund ecosystem growth" },
  ],
  dropxNote:
    "DROPX is strategic founder-level ecosystem development and is not part of the OnPro payable balance.",

  fbrc: [
    {
      id: "fbrc-transfer",
      label: "Site transfer & wholesale order expansion",
      amountCents: 150_000,
      status: "Pending — site not received, work not started",
    },
  ],
  fbrcNote:
    "Awaiting site handoff from previous developer. Nothing paid to date. One scope item ($1,500), pending. FBRC payments are separate from the OnPro cap.",
};
